apiVersion: v1
kind: Pod
metadata:
  name: memcahed-web
  labels:
   app: web
spec:
 containers:
  - name: memcahed
   image: memcached
   ports: 
   - containerPort: 11212
   resources:
     requests:
	 cpu: "0.35"
	 memory: "0.1561"
   imagePu;;Policy: IfNotPresent
restartPolicy: Never